[smtp]
enabled = true
host = in-v3.mailjet.com:587
user = ***REMOVED-ROTATED-MAILJET-API-KEY***
password = ***REMOVED-ROTATED-INTERNAL-GRAFANA-SECRET***
;cert_file =
;key_file =
skip_verify = false
from_address = password@vilevac.com
from_name = Vilevac Grafana Alerts
startTLS_policy = OpportunisticStartTLS
